/*REGISTRO DE ATENDIMENTO*/
SELECT PAC.COD_PAC,
       DECODE(PAC.DATA_ALTA, NULL, NULL,
              TO_DATE(TO_CHAR(PAC.DATA_ALTA, 'DD-MM-YYYY') || ' ' || TO_CHAR(PAC.HORA_ALTA, 'HH24:MI:SS'),
                      'DD-MM-YYYY HH24:MI:SS')) AS DATA_ALTA,
       TO_DATE(TO_CHAR(PAC.DATA_ENT, 'DD-MM-YYYY') || ' ' || TO_CHAR(PAC.HORA_ENT, 'HH24:MI:SS'),
               'DD-MM-YYYY HH24:MI:SS')         AS DATA_ENT,
       ALTA.DSC_MOT_ALTA,
       CO.COD_SET,
       CID.PK_UR_CID,
       ALTA.COD_MOT_ALTA,
       PAC.TIPO_PAC
FROM ADMWPD.FAPACCAD PAC
         INNER JOIN ADMWPD.MOTIVO_ALTA ALTA ON PAC.COD_MOT_ALTA = ALTA.COD_MOT_ALTA
         INNER JOIN ADMWPD.FAPACCOM CO ON CO.COD_PAC = PAC.COD_PAC
         INNER JOIN ADMWPD.URCIDCAD CID ON PAC.FK_UR_CID = CID.PK_UR_CID


/*LEITO*/
SELECT LEI.LEITO,
       LEI.DESCRICAO
FROM ADMWPD.FALEICAD LEI;

-- Leito histórico
select his.LEITO,
       his.COD_PAC,
       to_date(to_char(his.DATA, 'DD-MM-YYYY') || ' ' || to_char(his.HORA, 'HH24:MI:SS'), 'DD-MM-YYYY HH24:MI:SS') as data
from FALEHCAD his;

/*SETOR*/
SELECT
    DESCRICAO,
    TIPO_SETOR,
    COD_SET
FROM ADMWPD.FASETCAD;



/*COMANDA*/
select TIPO_COMANDA,
       COMANDA,
       COD_PAC,
       TO_DATE(TO_CHAR(DATA_MOV, 'DD-MM-YYYY') || ' ' || TO_CHAR(HORA_MOV, 'HH24:MI:SS'),
               'DD-MM-YYYY HH24:MI:SS') AS DATA_MOV,
       SET_ORI
from FAMOVCAD;



/*CID*/
SELECT
    CID.PK_UR_CID,
    CID.DIAGNOSTICO
FROM URCIDCAD CID;



/*PACIENTE*/
SELECT PAC.COD_PAC, PRT.NOME_PAC, PRT.SEXO, to_char(PRT.NASCIMENTO, 'DD-MM-YYYY') AS NASCIMENTO, PRT.NOME_MAE
FROM ADMWPD.FAPRTCAD PRT INNER JOIN ADMWPD.FAPACCAD PAC on PRT.COD_PRT = PAC.COD_PRT;



/*EXAME*/
select
    ex.COD_AGENDA,
    setor.COD_UNI,
    setor.COD_SALA,
    setor.DESCRICAO,
    to_char(EX.DATA, 'DD-MM-YYYY') || ' ' || TO_CHAR(EX.HORA_INI, 'HH24:MI:SS') AS DATA_INICIAL,
    to_char(EX.DATA, 'DD-MM-YYYY') || ' ' || TO_CHAR(EX.HORA_FIN, 'HH24:MI:SS') AS DATA_FINAL
from IMAGNCAD EX inner join ADMWPD.IMSALCAD setor on EX.COD_UNI = setor.COD_UNI and EX.COD_SALA = setor.COD_SALA;



/*MOTIVO ALTA*/
select ALTA.COD_MOT_ALTA, ALTA.DSC_MOT_ALTA
from ADMWPD.MOTIVO_ALTA ALTA;

