---
grails:
    profile: rest-api
    codegen:
        defaultPackage: br.com.hospitaldocoracaoal.aria
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    views:
        json:
            generator:
                dateFormat: 'yyyy-MM-dd HH:mm'
                timeZone: 'GMT-03:00'
    databinding:
        date-formats:
            - 'dd/MM/yyyy HH:mm'
            - 'yyyy-MM-dd HH:mm'
            - 'dd/MM/yyyy'
            - 'yyyy-MM-dd'
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
grails:
    cors:
        enabled: true
---

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.PostgreSQL94Dialect

environments:
    development:
        dataSource:
            logSql: true
            dbCreate: update
            url: jdbc:postgresql://10.10.1.23:5432/aria_dev
            username: aria
            password: 'aria@123-hcor'
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://10.10.1.23:5432/aria_dev
            username: aria
            password: 'aria@123-hcor'
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
grails:
    plugin:
        springsecurity:
            ldap:
                context:
                    managerDn: 'CN=Hsup,OU=SISTEMAS,OU=USUARIOS,OU=HCAL,DC=hcal,DC=lan'
                    managerPassword: 'Musicacomidatrabalhoh$up'
                    server: 'ldap://10.10.1.10'
                authorities:
                    ignorePartialResultException: true
                search:
                    base: 'dc=hcal,dc=lan'
                    filter: 'sAMAccountName={0}'
                    searchSubtree: true
                auth:
                    hideUserNotFoundExceptions: false

    mail:
        host: "smtp.gmail.com"
        port: 465
        username: "tihcal248@gmail.com"
        password: "tihcal123"
        props:
            mail.smtp.auth: "true"
            mail.smtp.socketFactory.port: "465"
            mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
            mail.smtp.socketFactory.fallback: "false"